name: Grammar Check for .tex files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  grammar-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install write-good
        run: npm install -g write-good

      - name: Find and check grammar in .tex files
        run: |
          for file in $(find src/tex -name "*.tex"); do
            echo "Checking grammar in $file"
            write-good $file
          done
